services:
  db:
    image: postgres:16.9-alpine
    container_name: muffinDB
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: muffin_wallet
    ports:
      - "54321:5432"
    volumes:
      - muffin_pg_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.97.1
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=1y"
    restart: unless-stopped

volumes:
  muffin_pg_data:
  vmdata:
