apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "muffin-currency.name" . }}
  template:
    metadata:
      labels:
        {{- include "muffin-currency.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "muffin-currency.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.httpGet.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.httpGet.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.httpGet.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.httpGet.periodSeconds }}
          envFrom:
            - configMapRef:
                name: {{ include "muffin-currency.fullname" . }}-configmap
