{{ if not .Values.useOnlyDeployment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    app.kubernetes.io/name: {{ include "muffin-currency.name" . }}
{{ end }}
