apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "muffin-wallet.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}